"""empty message

Revision ID: 053c270c3fb7
Revises: cfce4d1efeed
Create Date: 2019-02-25 11:35:15.787420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '053c270c3fb7'
down_revision = 'cfce4d1efeed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('lock_time', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assqt_locked',
    sa.Column('alock_id', sa.Integer(), nullable=False),
    sa.Column('assqt_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['alock_id'], ['alock.id'], ),
    sa.ForeignKeyConstraint(['assqt_id'], ['assqt.id'], ),
    sa.PrimaryKeyConstraint('alock_id', 'assqt_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assqt_locked')
    op.drop_table('alock')
    # ### end Alembic commands ###
