"""empty message

Revision ID: 1588b47a4a0c
Revises: 053c270c3fb7
Create Date: 2019-02-25 22:14:18.602176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1588b47a4a0c'
down_revision = '053c270c3fb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_admin')
    # ### end Alembic commands ###
