"""empty message

Revision ID: 45f8c0fec7b0
Revises: a74a638db58f
Create Date: 2019-02-25 00:55:37.533565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45f8c0fec7b0'
down_revision = 'a74a638db58f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assqt', sa.Column('checks_left', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assqt', 'checks_left')
    # ### end Alembic commands ###
