"""empty message

Revision ID: cfce4d1efeed
Revises: 466047f04164
Create Date: 2019-02-25 02:15:49.091155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfce4d1efeed'
down_revision = '466047f04164'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assqt_checked',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('assqt_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assqt_id'], ['assqt.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'assqt_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assqt_checked')
    # ### end Alembic commands ###
